name: Trigger & Wait
on:
  workflow_dispatch:
    inputs:
      base_url:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
        run: |
          echo "base_url: ${{ inputs.base_url }}"
          sleep 5